import React, { useState } from "react";
import {
  Link2,
  ExternalLink,
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Copy,
  Download,
  Check,
  RotateCcw,
  Search,
  Filter,
  ArrowUpRight,
  Sparkles,
  FileText,
  Globe,
  RefreshCw,
  SlidersHorizontal,
  Info,
  ShieldAlert,
  ListPlus,
  Compass
} from "lucide-react";
import { SeoToolDef } from "./seoToolsData";
import ToolShell from "./ToolShell";

interface BacklinkRecord {
  id: string;
  sourceUrl: string;
  targetUrl: string;
  anchorText: string;
  sourceDomainRating: number;
  linkType: "DoFollow" | "NoFollow" | "Sponsored" | "UGC";
  status: number;
  firstSeen: string;
  toxicityRisk: "Safe" | "Low" | "High";
  isSpam: boolean;
  hasLiveAnchor?: boolean;
}

interface IncomingLinkSummary {
  targetDomain: string;
  totalBacklinks: number;
  referringDomains: number;
  dofollowRatio: number;
  averageDomainRating: number;
  toxicityIndex: number; // 0 to 100
  isCleanNewProfile?: boolean;
  anchorDistribution: {
    branded: number;
    exactMatch: number;
    partialMatch: number;
    generic: number;
    nakedUrl: number;
  };
  links: BacklinkRecord[];
}

const BENCHMARK_SITES = [
  { label: "My Website (metazivo.com)", url: "https://metazivo.com" },
  { label: "Wikipedia (High Authority)", url: "https://wikipedia.org" },
  { label: "GitHub (Global Tech)", url: "https://github.com" }
];

interface Props {
  tool: SeoToolDef;
  onNavigateTool: (slug: string) => void;
  onNavigateHome: () => void;
}

export default function IncomingLinksCheckerTool({ tool, onNavigateTool, onNavigateHome }: Props) {
  const [activeTab, setActiveTab] = useState<"domain_search" | "verify_links">("domain_search");
  const [targetUrl, setTargetUrl] = useState("https://metazivo.com");
  const [customLinksText, setCustomLinksText] = useState("");
  const [isScanning, setIsScanning] = useState(false);
  const [data, setData] = useState<IncomingLinkSummary | null>(null);
  const [filterType, setFilterType] = useState<"All" | "DoFollow" | "NoFollow" | "Toxic" | "High Authority">("All");
  const [copiedDisavow, setCopiedDisavow] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const runBacklinkScan = async () => {
    if (!targetUrl.trim() && !customLinksText.trim()) {
      setErrorMsg("Please enter a target domain or paste backlink URLs to inspect.");
      return;
    }
    setIsScanning(true);
    setErrorMsg(null);

    let cleanUrl = targetUrl.trim();
    if (cleanUrl && !/^https?:\/\//i.test(cleanUrl)) {
      cleanUrl = "https://" + cleanUrl;
      setTargetUrl(cleanUrl);
    }

    const customLinksList = customLinksText
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => /^https?:\/\//i.test(l));

    try {
      const res = await fetch("/api/seo-tools/incoming-links", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          url: cleanUrl,
          customLinks: customLinksList
        })
      });

      if (res.ok) {
        const json = await res.json();
        setData(json);
      } else {
        const errJson = await res.json().catch(() => ({}));
        setErrorMsg(errJson.error || "Failed to inspect backlinks. Please try again.");
      }
    } catch (e: any) {
      setErrorMsg("Network error communicating with live backlink engine: " + (e.message || "Unknown error"));
    } finally {
      setIsScanning(false);
    }
  };

  // Filtered links
  const filteredLinks = data?.links.filter((l) => {
    if (filterType === "DoFollow") return l.linkType === "DoFollow";
    if (filterType === "NoFollow") return l.linkType === "NoFollow";
    if (filterType === "Toxic") return l.toxicityRisk === "High" || l.isSpam;
    if (filterType === "High Authority") return l.sourceDomainRating >= 70;
    return true;
  }) || [];

  // Export Disavow File for toxic links
  const generateDisavowContent = () => {
    if (!data) return "";
    const spamDomains = Array.from(
      new Set(
        data.links
          .filter((l) => l.isSpam || l.toxicityRisk === "High")
          .map((l) => {
            try {
              return `domain:${new URL(l.sourceUrl).hostname}`;
            } catch {
              return `domain:${l.sourceUrl}`;
            }
          })
      )
    );

    if (spamDomains.length === 0) {
      return "# Google Search Console Disavow File\n# No toxic incoming links detected for this domain. All active links appear safe.\n";
    }

    return `# Google Search Console Disavow File\n# Generated by Metazivo Incoming Links Checker\n# Date: ${new Date().toISOString().split("T")[0]}\n# Target: ${data.targetDomain}\n\n${spamDomains.join("\n")}\n`;
  };

  const handleCopyDisavow = () => {
    const text = generateDisavowContent();
    navigator.clipboard.writeText(text);
    setCopiedDisavow(true);
    setTimeout(() => setCopiedDisavow(false), 2000);
  };

  return (
    <ToolShell
      tool={tool}
      onNavigateTool={onNavigateTool}
      onNavigateHome={onNavigateHome}
      onReset={() => {
        setTargetUrl("https://metazivo.com");
        setCustomLinksText("");
        setData(null);
        setErrorMsg(null);
      }}
    >
      <div className="space-y-8">
        {/* Method Selector Tabs */}
        <div className="flex border-b border-slate-200 gap-2">
          <button
            onClick={() => setActiveTab("domain_search")}
            className={`pb-3 px-4 text-xs font-mono font-bold flex items-center gap-2 border-b-2 transition-all cursor-pointer ${
              activeTab === "domain_search"
                ? "border-[#FF5722] text-[#FF5722]"
                : "border-transparent text-slate-500 hover:text-slate-800"
            }`}
          >
            <Compass className="w-4 h-4" />
            <span>1. Live Search Index Scan (Whole Domain)</span>
          </button>
          <button
            onClick={() => setActiveTab("verify_links")}
            className={`pb-3 px-4 text-xs font-mono font-bold flex items-center gap-2 border-b-2 transition-all cursor-pointer ${
              activeTab === "verify_links"
                ? "border-[#FF5722] text-[#FF5722]"
                : "border-transparent text-slate-500 hover:text-slate-800"
            }`}
          >
            <ListPlus className="w-4 h-4" />
            <span>2. Verify Custom Backlink URLs / GSC Export</span>
          </button>
        </div>

        {/* Input Bar */}
        <div className="space-y-3">
          {activeTab === "domain_search" ? (
            <div>
              <label className="block text-xs font-mono font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                Target Domain or Webpage URL:
              </label>
              <div className="flex flex-col sm:flex-row items-stretch gap-2">
                <div className="relative flex-1">
                  <Globe className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
                  <input
                    type="url"
                    value={targetUrl}
                    onChange={(e) => setTargetUrl(e.target.value)}
                    placeholder="https://metazivo.com"
                    className="w-full bg-slate-50 border border-slate-200 rounded-2xl pl-10 pr-4 py-3 text-sm font-mono text-slate-900 focus:bg-white focus:outline-none focus:border-[#FF5722] transition-colors"
                  />
                </div>
                <button
                  onClick={runBacklinkScan}
                  disabled={isScanning}
                  className="px-6 py-3 bg-[#FF5722] hover:bg-[#FF7043] text-white rounded-2xl text-sm font-bold shadow-md shadow-orange-500/20 transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
                >
                  {isScanning ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      <span>Scanning Web Index...</span>
                    </>
                  ) : (
                    <>
                      <Search className="w-4 h-4" />
                      <span>Scan Live Inbound Links</span>
                    </>
                  )}
                </button>
              </div>

              {/* Quick presets */}
              <div className="flex items-center gap-2 flex-wrap pt-2">
                <span className="text-[11px] font-mono text-slate-400">Quick Test Domains:</span>
                {BENCHMARK_SITES.map((b, idx) => (
                  <button
                    key={idx}
                    onClick={() => {
                      setTargetUrl(b.url);
                    }}
                    className="text-[11px] font-mono px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-orange-50 hover:text-[#FF5722] text-slate-600 transition-colors cursor-pointer"
                  >
                    {b.label}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <label className="block text-xs font-mono font-bold text-slate-700 uppercase tracking-wider">
                  Paste Specific Backlink URLs (1 URL per line):
                </label>
                <span className="text-[11px] font-mono text-slate-400">
                  Target Domain: <span className="font-bold text-slate-700">{targetUrl}</span>
                </span>
              </div>
              <textarea
                rows={4}
                value={customLinksText}
                onChange={(e) => setCustomLinksText(e.target.value)}
                placeholder="https://example-blog.com/seo-article&#10;https://suspicious-directory.xyz/listing&#10;https://another-site.org/resource-page"
                className="w-full bg-slate-50 border border-slate-200 rounded-2xl p-3.5 text-xs font-mono text-slate-900 focus:bg-white focus:outline-none focus:border-[#FF5722] transition-colors"
              />
              <div className="flex justify-between items-center pt-1">
                <p className="text-[11px] text-slate-500 font-sans">
                  The engine will visit every URL in real time, extract the anchor text pointing to your domain, test HTTP status, and flag toxic spam risks.
                </p>
                <button
                  onClick={runBacklinkScan}
                  disabled={isScanning}
                  className="px-6 py-2.5 bg-[#FF5722] hover:bg-[#FF7043] text-white rounded-xl text-xs font-mono font-bold shadow-md shadow-orange-500/20 transition-all flex items-center gap-2 cursor-pointer disabled:opacity-50 shrink-0"
                >
                  {isScanning ? (
                    <>
                      <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                      <span>Verifying URLs...</span>
                    </>
                  ) : (
                    <>
                      <ShieldCheck className="w-3.5 h-3.5" />
                      <span>Audit Backlink Toxicity</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          )}

          {errorMsg && (
            <div className="p-3 bg-red-50 text-red-700 text-xs rounded-xl border border-red-200 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 shrink-0" />
              <span>{errorMsg}</span>
            </div>
          )}
        </div>

        {/* Results Dashboard */}
        {data && (
          <div className="space-y-8 animate-fade-in">
            {/* Top Metric Cards */}
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 sm:gap-4">
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-1">
                <span className="text-[11px] font-mono uppercase text-slate-500 font-semibold">Total Inbound</span>
                <div className="text-2xl font-extrabold text-slate-900 font-mono">
                  {data.totalBacklinks.toLocaleString()}
                </div>
                <span className="text-[10px] text-slate-500 font-mono">
                  {data.totalBacklinks === 0 ? "No Backlinks Found" : "Indexed Backlinks"}
                </span>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-1">
                <span className="text-[11px] font-mono uppercase text-slate-500 font-semibold">Referring Domains</span>
                <div className="text-2xl font-extrabold text-slate-900 font-mono">
                  {data.referringDomains.toLocaleString()}
                </div>
                <span className="text-[10px] text-slate-500 font-mono">Unique Root Hosts</span>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-1">
                <span className="text-[11px] font-mono uppercase text-slate-500 font-semibold">DoFollow Ratio</span>
                <div className="text-2xl font-extrabold text-[#FF5722] font-mono">
                  {data.dofollowRatio}%
                </div>
                <span className="text-[10px] text-slate-500 font-mono">Equity Passing</span>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-1">
                <span className="text-[11px] font-mono uppercase text-slate-500 font-semibold">Avg Domain Rating</span>
                <div className="text-2xl font-extrabold text-slate-900 font-mono">
                  {data.averageDomainRating}/100
                </div>
                <span className="text-[10px] text-blue-600 font-mono">Authority Benchmark</span>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-1">
                <span className="text-[11px] font-mono uppercase text-slate-500 font-semibold">Toxicity Index</span>
                <div className={`text-2xl font-extrabold font-mono ${data.toxicityIndex > 25 ? "text-red-600" : "text-emerald-600"}`}>
                  {data.toxicityIndex}/100
                </div>
                <span className="text-[10px] text-emerald-600 font-mono">
                  {data.toxicityIndex === 0 ? "100% Clean" : data.toxicityIndex <= 15 ? "Low Risk" : "High Risk"}
                </span>
              </div>
            </div>

            {/* If 0 backlinks detected (Authentic clean new site) */}
            {data.totalBacklinks === 0 && (
              <div className="p-6 bg-emerald-50/80 border border-emerald-200 rounded-3xl space-y-3">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-full bg-emerald-500 text-white flex items-center justify-center shrink-0">
                    <CheckCircle2 className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-emerald-950 font-sans">
                      Clean Domain Profile — Zero Toxic Links Detected
                    </h4>
                    <span className="text-xs text-emerald-700 font-mono">
                      Domain: {data.targetDomain} • Index Status: Clean / Fresh
                    </span>
                  </div>
                </div>
                <p className="text-xs text-emerald-900 font-sans leading-relaxed">
                  Our live search index scan did not detect any external inbound links pointing to <strong>{data.targetDomain}</strong>. 
                  If you have not built backlinks yet, having <strong>0 backlinks is completely normal, accurate, and healthy</strong>. 
                  Your domain is 100% free of spam links, toxic PBN networks, and algorithmic Google Penguin penalties.
                </p>
                <div className="pt-2 text-xs text-emerald-800 font-sans flex flex-wrap gap-4">
                  <span>💡 <strong>Tip:</strong> Earn your first authoritative backlinks by claiming your Google Business Profile, submitting to Clutch, and sharing original industry research.</span>
                </div>
              </div>
            )}

            {/* Anchor Text Distribution (Only shown when backlinks exist) */}
            {data.totalBacklinks > 0 && (
              <div className="bg-white border border-slate-200/90 rounded-3xl p-6 space-y-4">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="space-y-1">
                    <span className="text-xs font-mono font-bold uppercase text-[#FF5722]">
                      Natural Link Graph Audit
                    </span>
                    <h4 className="text-base font-bold text-slate-900">
                      Anchor Text Distribution & Penguin Penalty Safety
                    </h4>
                  </div>

                  <div className="flex items-center gap-1.5 text-xs font-mono">
                    {data.anchorDistribution.exactMatch <= 15 ? (
                      <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200 font-semibold">
                        <CheckCircle2 className="w-3.5 h-3.5" /> Healthy Distribution (Low Risk)
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-amber-50 text-amber-700 border border-amber-200 font-semibold">
                        <AlertTriangle className="w-3.5 h-3.5" /> Over-Optimization Risk (&gt;15% Exact Match)
                      </span>
                    )}
                  </div>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 pt-2">
                  <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/70">
                    <div className="text-[11px] text-slate-500 font-mono">Branded Anchors</div>
                    <div className="text-lg font-bold text-slate-900 font-mono">{data.anchorDistribution.branded}%</div>
                    <div className="text-[10px] text-slate-400">Target: 40–60%</div>
                  </div>

                  <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/70">
                    <div className="text-[11px] text-slate-500 font-mono">Exact Match</div>
                    <div className="text-lg font-bold text-slate-900 font-mono">{data.anchorDistribution.exactMatch}%</div>
                    <div className="text-[10px] text-slate-400">Target: &lt;15%</div>
                  </div>

                  <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/70">
                    <div className="text-[11px] text-slate-500 font-mono">Partial Match</div>
                    <div className="text-lg font-bold text-slate-900 font-mono">{data.anchorDistribution.partialMatch}%</div>
                    <div className="text-[10px] text-slate-400">Target: 20–30%</div>
                  </div>

                  <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/70">
                    <div className="text-[11px] text-slate-500 font-mono">Generic ("click here")</div>
                    <div className="text-lg font-bold text-slate-900 font-mono">{data.anchorDistribution.generic}%</div>
                    <div className="text-[10px] text-slate-400">Target: 5–15%</div>
                  </div>

                  <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/70">
                    <div className="text-[11px] text-slate-500 font-mono">Naked URL</div>
                    <div className="text-lg font-bold text-slate-900 font-mono">{data.anchorDistribution.nakedUrl}%</div>
                    <div className="text-[10px] text-slate-400">Target: 5–15%</div>
                  </div>
                </div>
              </div>
            )}

            {/* Filterable Inbound Links Inventory Table (if links exist) */}
            {data.links.length > 0 && (
              <div className="space-y-4">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <h4 className="text-base font-bold text-slate-900 flex items-center gap-2">
                    <Link2 className="w-4 h-4 text-[#FF5722]" />
                    <span>Verified Referring Links ({filteredLinks.length} Displayed)</span>
                  </h4>

                  <div className="flex items-center gap-1.5 flex-wrap">
                    {(["All", "DoFollow", "NoFollow", "High Authority", "Toxic"] as const).map((filter) => (
                      <button
                        key={filter}
                        onClick={() => setFilterType(filter)}
                        className={`px-3 py-1 rounded-lg text-xs font-mono font-bold transition-colors cursor-pointer ${
                          filterType === filter
                            ? "bg-[#FF5722] text-white"
                            : "bg-slate-100 hover:bg-slate-200 text-slate-700"
                        }`}
                      >
                        {filter}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="overflow-x-auto border border-slate-200 rounded-2xl">
                  <table className="w-full text-left text-xs text-slate-700">
                    <thead className="bg-slate-50 text-slate-600 uppercase font-mono text-[10px] tracking-wider border-b border-slate-200">
                      <tr>
                        <th className="py-3 px-3">Referring Source URL</th>
                        <th className="py-3 px-2 w-16 text-center">DR</th>
                        <th className="py-3 px-3">Anchor Text</th>
                        <th className="py-3 px-2 w-24">Link Type</th>
                        <th className="py-3 px-2 w-20 text-center">Status</th>
                        <th className="py-3 px-2 w-24 text-center">Toxicity Risk</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 font-sans">
                      {filteredLinks.map((link) => (
                        <tr key={link.id} className="hover:bg-slate-50/70">
                          <td className="py-2.5 px-3">
                            <a
                              href={link.sourceUrl}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="font-mono text-xs text-slate-800 hover:text-[#FF5722] font-semibold transition-colors flex items-center gap-1 line-clamp-1"
                            >
                              {link.sourceUrl} <ArrowUpRight className="w-3 h-3 text-slate-400 shrink-0" />
                            </a>
                            <div className="text-[10px] text-slate-400 font-mono mt-0.5">
                              {link.hasLiveAnchor ? "✅ Hyperlink verified on page" : "ℹ️ Web citation / Mention"}
                            </div>
                          </td>
                          <td className="py-2.5 px-2 text-center font-mono font-bold text-slate-800">
                            {link.sourceDomainRating}
                          </td>
                          <td className="py-2.5 px-3">
                            <span className="font-semibold text-slate-900 bg-slate-100 px-2 py-0.5 rounded text-xs">
                              "{link.anchorText}"
                            </span>
                          </td>
                          <td className="py-2.5 px-2">
                            <span
                              className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold ${
                                link.linkType === "DoFollow"
                                  ? "bg-emerald-50 text-emerald-700 border border-emerald-200"
                                  : "bg-slate-100 text-slate-600"
                              }`}
                            >
                              {link.linkType}
                            </span>
                          </td>
                          <td className="py-2.5 px-2 text-center font-mono font-bold">
                            <span className={link.status === 200 ? "text-emerald-600" : "text-amber-600"}>
                              {link.status === 0 ? "Timeout" : link.status}
                            </span>
                          </td>
                          <td className="py-2.5 px-2 text-center">
                            <span
                              className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold ${
                                link.toxicityRisk === "High"
                                  ? "bg-red-50 text-red-700 border border-red-200"
                                  : link.toxicityRisk === "Low"
                                  ? "bg-amber-50 text-amber-700 border border-amber-200"
                                  : "bg-emerald-50 text-emerald-700 border border-emerald-200"
                              }`}
                            >
                              {link.toxicityRisk === "High" ? "🚨 Toxic" : link.toxicityRisk}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Disavow Generator Callout */}
            <div className="bg-slate-900 text-white rounded-3xl p-6 sm:p-8 space-y-4 shadow-sm">
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div className="space-y-1">
                  <span className="text-xs font-mono font-bold uppercase tracking-wider text-orange-400">
                    Google Disavow Tool Export
                  </span>
                  <h4 className="text-lg font-bold text-white">
                    GSC Compatible Disavow File for High-Risk Referral Links
                  </h4>
                  <p className="text-xs text-slate-300 font-sans max-w-xl">
                    Copy and upload this disavow file directly into Google Search Console to instruct Googlebot to ignore toxic scraper links and protect your domain against manual actions.
                  </p>
                </div>

                <button
                  onClick={handleCopyDisavow}
                  className="px-4 py-2.5 rounded-xl bg-[#FF5722] hover:bg-[#FF7043] text-white text-xs font-mono font-bold transition-colors cursor-pointer flex items-center gap-2"
                >
                  {copiedDisavow ? (
                    <>
                      <Check className="w-4 h-4 text-white" />
                      <span>Copied disavow.txt!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      <span>Copy disavow.txt</span>
                    </>
                  )}
                </button>
              </div>

              <pre className="p-4 bg-slate-950 text-slate-300 rounded-2xl text-xs font-mono overflow-x-auto border border-slate-800">
                {generateDisavowContent()}
              </pre>
            </div>
          </div>
        )}

        {/* Step-by-Step Educational Playbook */}
        <div className="bg-white border border-slate-200/80 rounded-3xl p-6 sm:p-8 space-y-6">
          <div className="space-y-1">
            <span className="text-xs font-mono font-bold text-[#FF5722] uppercase tracking-widest">
              Step-by-Step Acquisition Strategy
            </span>
            <h3 className="text-xl font-extrabold text-slate-950">
              How to Earn High-Authority Inbound Links in 2026
            </h3>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 text-xs text-slate-700 leading-relaxed font-sans">
            <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200/70 space-y-2">
              <div className="w-7 h-7 rounded-xl bg-orange-100 text-[#FF5722] font-mono font-bold flex items-center justify-center">
                01
              </div>
              <h4 className="font-bold text-slate-900 text-sm">Publish Data & Interactive Tools</h4>
              <p>
                Original research, free calculators, and benchmark surveys naturally attract editorial inbound links from industry journalists without paid outreach.
              </p>
            </div>

            <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200/70 space-y-2">
              <div className="w-7 h-7 rounded-xl bg-orange-100 text-[#FF5722] font-mono font-bold flex items-center justify-center">
                02
              </div>
              <h4 className="font-bold text-slate-900 text-sm">Reclaim Broken Inbound Links</h4>
              <p>
                Find 404 dead links pointing to your domain from external sites and implement 301 redirects to recover lost link equity instantly.
              </p>
            </div>

            <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200/70 space-y-2">
              <div className="w-7 h-7 rounded-xl bg-orange-100 text-[#FF5722] font-mono font-bold flex items-center justify-center">
                03
              </div>
              <h4 className="font-bold text-slate-900 text-sm">E-E-A-T & Brand Mentions</h4>
              <p>
                AI Search engines cite domains with consistent brand co-occurrences on trusted review hubs (Clutch, Trustpilot, Crunchbase, Wikipedia).
              </p>
            </div>
          </div>
        </div>
      </div>
    </ToolShell>
  );
}
