import React, { useState } from "react";
import {
  FileCode,
  Copy,
  Download,
  Check,
  RotateCcw,
  Plus,
  Trash2,
  ShieldAlert,
  CheckCircle2,
  XCircle,
  Search,
  Globe
} from "lucide-react";
import { SeoToolDef } from "./seoToolsData";
import ToolShell from "./ToolShell";

interface Props {
  tool: SeoToolDef;
  onNavigateTool: (slug: string) => void;
  onNavigateHome: () => void;
}

export default function RobotsTxtTool({ tool, onNavigateTool, onNavigateHome }: Props) {
  const [activeTab, setActiveTab] = useState<"generator" | "tester">("generator");

  // Generator State
  const [sitemapUrl, setSitemapUrl] = useState("https://example.com/sitemap.xml");
  const [crawlDelay, setCrawlDelay] = useState("");
  const [blockAiBots, setBlockAiBots] = useState(false);
  const [rules, setRules] = useState<Array<{ agent: string; disallow: string[]; allow: string[] }>>([
    {
      agent: "*",
      disallow: ["/admin/", "/private/", "/cart/", "/checkout/", "/*?*utm_*"],
      allow: ["/wp-admin/admin-ajax.php", "/public/"]
    }
  ]);
  const [copied, setCopied] = useState(false);

  // Tester State
  const [testDomain, setTestDomain] = useState("");
  const [testPath, setTestPath] = useState("/admin/dashboard");
  const [testUserAgent, setTestUserAgent] = useState("Googlebot");
  const [testerRobotsContent, setTesterRobotsContent] = useState("");
  const [testing, setTesting] = useState(false);
  const [testResult, setTestResult] = useState<{ allowed: boolean; matchedRule?: string } | null>(null);

  // Build robots.txt string
  const generateRobotsTxt = () => {
    let lines: string[] = [];
    lines.push("# robots.txt generated by Metazivo SEO Platform (https://metazivo.com)");
    lines.push("");

    rules.forEach((group) => {
      lines.push(`User-agent: ${group.agent}`);
      if (crawlDelay) {
        lines.push(`Crawl-delay: ${crawlDelay}`);
      }
      group.disallow.forEach((path) => {
        if (path.trim()) lines.push(`Disallow: ${path.trim()}`);
      });
      group.allow.forEach((path) => {
        if (path.trim()) lines.push(`Allow: ${path.trim()}`);
      });
      lines.push("");
    });

    if (blockAiBots) {
      lines.push("# Block Common AI LLM Scrapers");
      ["GPTBot", "ChatGPT-User", "CCBot", "ClaudeBot", "anthropic-ai"].forEach((bot) => {
        lines.push(`User-agent: ${bot}`);
        lines.push("Disallow: /");
        lines.push("");
      });
    }

    if (sitemapUrl.trim()) {
      lines.push(`Sitemap: ${sitemapUrl.trim()}`);
    }

    return lines.join("\n");
  };

  const robotsOutput = generateRobotsTxt();

  const handleCopy = () => {
    navigator.clipboard.writeText(robotsOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([robotsOutput], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "robots.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const addDisallowRule = (groupIndex: number) => {
    const updated = [...rules];
    updated[groupIndex].disallow.push("/");
    setRules(updated);
  };

  const removeDisallowRule = (groupIndex: number, ruleIndex: number) => {
    const updated = [...rules];
    updated[groupIndex].disallow = updated[groupIndex].disallow.filter((_, i) => i !== ruleIndex);
    setRules(updated);
  };

  const addAllowRule = (groupIndex: number) => {
    const updated = [...rules];
    updated[groupIndex].allow.push("/");
    setRules(updated);
  };

  const removeAllowRule = (groupIndex: number, ruleIndex: number) => {
    const updated = [...rules];
    updated[groupIndex].allow = updated[groupIndex].allow.filter((_, i) => i !== ruleIndex);
    setRules(updated);
  };

  // Live Tester Fetch
  const handleFetchAndTest = async () => {
    setTesting(true);
    let contentToTest = testerRobotsContent;

    if (testDomain.trim()) {
      try {
        const resp = await fetch("/api/seo-tools/fetch-robots", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ url: testDomain })
        });
        const data = await resp.json();
        if (data.content) {
          contentToTest = data.content;
          setTesterRobotsContent(data.content);
        }
      } catch (e) {
        console.error("Failed to fetch remote robots.txt", e);
      }
    }

    if (!contentToTest) {
      contentToTest = robotsOutput;
      setTesterRobotsContent(robotsOutput);
    }

    // Evaluate matching
    const lines = contentToTest.split("\n");
    let currentAgent = "";
    let isDisallowed = false;
    let matched = "";

    const pathToCheck = testPath.startsWith("/") ? testPath : "/" + testPath;

    for (let line of lines) {
      const clean = line.split("#")[0].trim();
      if (!clean) continue;

      if (/^User-agent:\s*(.+)$/i.test(clean)) {
        currentAgent = clean.replace(/^User-agent:\s*/i, "").trim();
      }

      if (currentAgent === "*" || currentAgent.toLowerCase() === testUserAgent.toLowerCase()) {
        if (/^Disallow:\s*(.+)$/i.test(clean)) {
          const rulePath = clean.replace(/^Disallow:\s*/i, "").trim();
          if (rulePath && pathToCheck.startsWith(rulePath)) {
            isDisallowed = true;
            matched = `Disallow: ${rulePath} (under User-agent: ${currentAgent})`;
          }
        }
        if (/^Allow:\s*(.+)$/i.test(clean)) {
          const rulePath = clean.replace(/^Allow:\s*/i, "").trim();
          if (rulePath && pathToCheck.startsWith(rulePath)) {
            isDisallowed = false;
            matched = `Allow: ${rulePath} (under User-agent: ${currentAgent})`;
          }
        }
      }
    }

    setTestResult({
      allowed: !isDisallowed,
      matchedRule: matched || "Default Allow (no matching Disallow rule found)"
    });
    setTesting(false);
  };

  return (
    <ToolShell
      tool={tool}
      onNavigateTool={onNavigateTool}
      onNavigateHome={onNavigateHome}
    >
      <div className="space-y-8">
        {/* Navigation Tabs */}
        <div className="inline-flex p-1 bg-slate-100 rounded-xl text-xs font-semibold text-slate-600">
          <button
            type="button"
            onClick={() => setActiveTab("generator")}
            className={`px-4 py-2 rounded-lg transition-all cursor-pointer ${
              activeTab === "generator" ? "bg-white text-slate-900 shadow-xs font-bold" : "hover:text-slate-900"
            }`}
          >
            Robots.txt Generator
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("tester")}
            className={`px-4 py-2 rounded-lg transition-all cursor-pointer ${
              activeTab === "tester" ? "bg-white text-slate-900 shadow-xs font-bold" : "hover:text-slate-900"
            }`}
          >
            Live Robots.txt Tester
          </button>
        </div>

        {activeTab === "generator" ? (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            {/* Left Controls */}
            <div className="lg:col-span-6 space-y-5">
              <div className="space-y-2">
                <label className="block text-xs font-mono font-bold text-slate-700 uppercase tracking-wider">
                  XML Sitemap URL
                </label>
                <input
                  type="text"
                  value={sitemapUrl}
                  onChange={(e) => setSitemapUrl(e.target.value)}
                  placeholder="https://example.com/sitemap.xml"
                  className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs font-mono focus:bg-white focus:outline-none focus:ring-1 focus:ring-[#FF5722]"
                />
              </div>

              {/* AI Scrapers Toggle */}
              <div className="p-4 rounded-xl bg-orange-50/50 border border-orange-200/80 flex items-center justify-between gap-3">
                <div className="space-y-0.5">
                  <span className="font-bold text-xs text-slate-900 flex items-center gap-1.5">
                    <ShieldAlert className="w-4 h-4 text-[#FF5722]" />
                    Block AI Scrapers (GPTBot, CCBot, ClaudeBot)
                  </span>
                  <p className="text-[11px] text-slate-500">
                    Prevents automated LLM crawlers from scraping your content for model training.
                  </p>
                </div>
                <input
                  type="checkbox"
                  checked={blockAiBots}
                  onChange={(e) => setBlockAiBots(e.target.checked)}
                  className="w-4 h-4 accent-[#FF5722] cursor-pointer"
                />
              </div>

              {/* Rules List */}
              <div className="space-y-4">
                {rules.map((rule, gIdx) => (
                  <div key={gIdx} className="p-4 bg-slate-50 rounded-2xl border border-slate-200 space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-slate-800">
                        Target User-Agent: <strong className="text-[#FF5722] font-mono">{rule.agent}</strong>
                      </span>
                    </div>

                    {/* Disallow rules */}
                    <div className="space-y-1.5">
                      <div className="flex items-center justify-between">
                        <span className="text-[11px] font-mono font-bold text-rose-600 uppercase">
                          Disallow Directives
                        </span>
                        <button
                          type="button"
                          onClick={() => addDisallowRule(gIdx)}
                          className="text-[11px] text-slate-600 hover:text-slate-900 font-semibold cursor-pointer flex items-center gap-1"
                        >
                          <Plus className="w-3 h-3" /> Add Path
                        </button>
                      </div>
                      {rule.disallow.map((path, rIdx) => (
                        <div key={rIdx} className="flex items-center gap-2">
                          <input
                            type="text"
                            value={path}
                            onChange={(e) => {
                              const updated = [...rules];
                              updated[gIdx].disallow[rIdx] = e.target.value;
                              setRules(updated);
                            }}
                            className="flex-1 p-2 bg-white border border-slate-200 rounded-lg text-xs font-mono"
                          />
                          <button
                            type="button"
                            onClick={() => removeDisallowRule(gIdx, rIdx)}
                            className="text-slate-400 hover:text-rose-600 p-1 cursor-pointer"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      ))}
                    </div>

                    {/* Allow rules */}
                    <div className="space-y-1.5 pt-2 border-t border-slate-200">
                      <div className="flex items-center justify-between">
                        <span className="text-[11px] font-mono font-bold text-emerald-600 uppercase">
                          Allow Directives
                        </span>
                        <button
                          type="button"
                          onClick={() => addAllowRule(gIdx)}
                          className="text-[11px] text-slate-600 hover:text-slate-900 font-semibold cursor-pointer flex items-center gap-1"
                        >
                          <Plus className="w-3 h-3" /> Add Path
                        </button>
                      </div>
                      {rule.allow.map((path, rIdx) => (
                        <div key={rIdx} className="flex items-center gap-2">
                          <input
                            type="text"
                            value={path}
                            onChange={(e) => {
                              const updated = [...rules];
                              updated[gIdx].allow[rIdx] = e.target.value;
                              setRules(updated);
                            }}
                            className="flex-1 p-2 bg-white border border-slate-200 rounded-lg text-xs font-mono"
                          />
                          <button
                            type="button"
                            onClick={() => removeAllowRule(gIdx, rIdx)}
                            className="text-slate-400 hover:text-rose-600 p-1 cursor-pointer"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Right Preview */}
            <div className="lg:col-span-6 space-y-4 flex flex-col justify-between">
              <div className="flex items-center justify-between flex-wrap gap-2">
                <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-700">
                  Preview Generated robots.txt
                </h3>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleCopy}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 text-xs font-medium cursor-pointer"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
                    <span>{copied ? "Copied" : "Copy"}</span>
                  </button>
                  <button
                    type="button"
                    onClick={handleDownload}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 text-xs font-medium cursor-pointer"
                  >
                    <Download className="w-3.5 h-3.5 text-slate-400" />
                    <span>Download robots.txt</span>
                  </button>
                </div>
              </div>

              <div className="rounded-2xl bg-slate-950 p-4 border border-slate-800 text-slate-100 font-mono text-xs overflow-x-auto min-h-[340px] shadow-inner">
                <pre className="whitespace-pre-wrap leading-relaxed">
                  <code>{robotsOutput}</code>
                </pre>
              </div>

              <p className="text-[11px] text-slate-500 font-mono">
                Place this file directly in the public root folder of your web server (e.g. https://yourdomain.com/robots.txt).
              </p>
            </div>
          </div>
        ) : (
          /* Live Tester View */
          <div className="space-y-6">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="space-y-1">
                <label className="block text-xs font-mono font-bold text-slate-700 uppercase">
                  Remote Domain (Optional)
                </label>
                <input
                  type="text"
                  placeholder="https://example.com"
                  value={testDomain}
                  onChange={(e) => setTestDomain(e.target.value)}
                  className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs font-sans"
                />
              </div>

              <div className="space-y-1">
                <label className="block text-xs font-mono font-bold text-slate-700 uppercase">
                  Path to Test
                </label>
                <input
                  type="text"
                  placeholder="/admin/users"
                  value={testPath}
                  onChange={(e) => setTestPath(e.target.value)}
                  className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs font-mono"
                />
              </div>

              <div className="space-y-1">
                <label className="block text-xs font-mono font-bold text-slate-700 uppercase">
                  Bot / User-Agent
                </label>
                <select
                  value={testUserAgent}
                  onChange={(e) => setTestUserAgent(e.target.value)}
                  className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs font-sans cursor-pointer"
                >
                  <option value="Googlebot">Googlebot</option>
                  <option value="Bingbot">Bingbot</option>
                  <option value="GPTBot">GPTBot (OpenAI)</option>
                  <option value="ClaudeBot">ClaudeBot (Anthropic)</option>
                  <option value="*">All Bots (*)</option>
                </select>
              </div>
            </div>

            <div className="flex justify-end">
              <button
                type="button"
                onClick={handleFetchAndTest}
                disabled={testing}
                className="px-6 py-2.5 bg-[#FF5722] hover:bg-[#FF7043] text-white rounded-xl text-xs font-bold transition-all flex items-center gap-2 cursor-pointer disabled:opacity-50"
              >
                {testing ? (
                  <>
                    <div className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    <span>Evaluating Directives...</span>
                  </>
                ) : (
                  <>
                    <Search className="w-3.5 h-3.5" />
                    <span>Test Path Access</span>
                  </>
                )}
              </button>
            </div>

            {testResult && (
              <div
                className={`p-5 rounded-2xl border flex items-start gap-3 animate-fade-in text-xs font-sans ${
                  testResult.allowed
                    ? "bg-emerald-50 border-emerald-200 text-emerald-900"
                    : "bg-rose-50 border-rose-200 text-rose-900"
                }`}
              >
                {testResult.allowed ? (
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                ) : (
                  <XCircle className="w-5 h-5 text-rose-600 shrink-0 mt-0.5" />
                )}
                <div className="space-y-1">
                  <h4 className="font-bold text-sm">
                    {testResult.allowed
                      ? `Access ALLOWED for ${testUserAgent}`
                      : `Access BLOCKED (DISALLOWED) for ${testUserAgent}`}
                  </h4>
                  <p className="text-xs opacity-90">
                    <strong>Evaluated path:</strong> <span className="font-mono">{testPath}</span>
                  </p>
                  <p className="text-xs opacity-90">
                    <strong>Rule match:</strong> <span className="font-mono">{testResult.matchedRule}</span>
                  </p>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </ToolShell>
  );
}
