import React, { useState } from "react";
import {
  Globe,
  Search,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Clock,
  ArrowRight,
  Copy,
  Download,
  Check,
  ShieldCheck,
  Zap,
  Share2,
  FileCode,
  Layout,
  ExternalLink
} from "lucide-react";
import { SeoToolDef } from "./seoToolsData";
import ToolShell from "./ToolShell";

interface AuditResult {
  url: string;
  requestedUrl: string;
  httpStatus: number;
  responseTimeMs: number;
  overallScore: number;
  scores: {
    overall: number;
    technical: number;
    onPage: number;
    content: number;
    performance: number;
    social: number;
    structuredData: number;
  };
  metadata: {
    title: string;
    titleLength: number;
    description: string;
    descriptionLength: number;
    canonical: string;
    robotsMeta: string;
    hasViewport: boolean;
    isHttps: boolean;
    wordCount: number;
  };
  headings: {
    h1Count: number;
    h1List: string[];
    h2Count: number;
    h2List: string[];
  };
  media: {
    totalImages: number;
    missingAltImages: number;
    sampleMissingAlts: string[];
  };
  links: {
    internalLinks: number;
    externalLinks: number;
  };
  social: {
    openGraph: {
      title: string;
      description: string;
      image: string;
      url: string;
      type: string;
      present: boolean;
    };
    twitterCard: {
      card: string;
      title: string;
      image: string;
      present: boolean;
    };
  };
  structuredData: {
    count: number;
    types: string[];
  };
  issues: Array<{
    id: string;
    title: string;
    severity: "critical" | "warning" | "good";
    category: "Technical" | "On-Page" | "Content" | "Performance" | "Social" | "Structured Data";
    whyItMatters: string;
    howToFix: string;
  }>;
}

interface Props {
  tool: SeoToolDef;
  onNavigateTool: (slug: string) => void;
  onNavigateHome: () => void;
}

export default function SeoAuditTool({ tool, onNavigateTool, onNavigateHome }: Props) {
  const [urlInput, setUrlInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AuditResult | null>(null);
  const [activeTab, setActiveTab] = useState<"all" | "critical" | "warning" | "good">("all");
  const [copiedReport, setCopiedReport] = useState(false);

  const handleAudit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    let target = urlInput.trim();
    if (!target) {
      setError("Please enter a valid website URL");
      return;
    }
    if (!/^https?:\/\//i.test(target)) {
      target = "https://" + target;
      setUrlInput(target);
    }

    setLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/seo-tools/audit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: target })
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || "Failed to analyze website");
      }

      setResult(data);
    } catch (err: any) {
      setError(err.message || "Could not connect to target website. Please ensure URL is accessible.");
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setUrlInput("");
    setResult(null);
    setError(null);
  };

  const copyReport = () => {
    if (!result) return;
    const summary = `=== SEO AUDIT REPORT FOR ${result.url} ===
Overall Score: ${result.overallScore}/100
Technical Score: ${result.scores.technical}/100
On-Page Score: ${result.scores.onPage}/100
Performance Score: ${result.scores.performance}/100
Structured Data Score: ${result.scores.structuredData}/100

Metadata:
- Title: ${result.metadata.title} (${result.metadata.titleLength} chars)
- Description: ${result.metadata.description} (${result.metadata.descriptionLength} chars)
- Canonical: ${result.metadata.canonical || "None"}
- H1 Count: ${result.headings.h1Count}
- Images Missing Alt: ${result.media.missingAltImages}/${result.media.totalImages}

Critical Issues (${result.issues.filter(i => i.severity === 'critical').length}):
${result.issues.filter(i => i.severity === 'critical').map(i => `- ${i.title}: ${i.howToFix}`).join("\n")}

Generated by Metazivo SEO Platform (https://metazivo.com)`;

    navigator.clipboard.writeText(summary);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2000);
  };

  const downloadReport = () => {
    if (!result) return;
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `seo-audit-${new URL(result.url).hostname}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const getScoreColor = (score: number) => {
    if (score >= 85) return "text-emerald-600 border-emerald-500 bg-emerald-50";
    if (score >= 60) return "text-amber-600 border-amber-500 bg-amber-50";
    return "text-rose-600 border-rose-500 bg-rose-50";
  };

  const filteredIssues = result?.issues.filter((issue) => {
    if (activeTab === "all") return true;
    return issue.severity === activeTab;
  }) || [];

  return (
    <ToolShell
      tool={tool}
      onNavigateTool={onNavigateTool}
      onNavigateHome={onNavigateHome}
      onReset={result ? handleReset : undefined}
    >
      <div className="space-y-8">
        {/* URL Input Form */}
        <form onSubmit={handleAudit} className="space-y-3">
          <label htmlFor="audit-url-input" className="block text-xs font-mono font-bold text-slate-700 uppercase tracking-wider">
            Target Website or Web Page URL
          </label>
          <div className="flex flex-col sm:flex-row gap-3">
            <div className="relative flex-1">
              <Globe className="w-5 h-5 text-slate-400 absolute left-4 top-1/2 -translate-y-1/2 pointer-events-none" />
              <input
                id="audit-url-input"
                type="text"
                placeholder="https://example.com"
                value={urlInput}
                onChange={(e) => setUrlInput(e.target.value)}
                disabled={loading}
                className="w-full pl-12 pr-4 py-3.5 bg-slate-50/70 border border-slate-200 rounded-xl text-sm text-slate-900 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#FF5722]/30 focus:border-[#FF5722] transition-all font-sans"
              />
            </div>
            <button
              type="submit"
              disabled={loading}
              className="px-7 py-3.5 bg-[#FF5722] hover:bg-[#FF7043] text-white rounded-xl text-xs font-bold transition-all shadow-[0_4px_16px_rgba(255,87,34,0.25)] flex items-center justify-center gap-2 cursor-pointer shrink-0 disabled:opacity-50"
            >
              {loading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span>Crawling & Analyzing...</span>
                </>
              ) : (
                <>
                  <Search className="w-4 h-4" />
                  <span>Run Full SEO Audit</span>
                </>
              )}
            </button>
          </div>
          <p className="text-[11px] text-slate-400 font-mono">
            Analyzes HTTP status, response time, meta tags, heading structure, alt text, open graph, canonicalization, and schemas.
          </p>
        </form>

        {/* Error Alert */}
        {error && (
          <div className="p-4 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs flex items-start gap-3 animate-fade-in">
            <XCircle className="w-4 h-4 shrink-0 mt-0.5 text-rose-500" />
            <div className="space-y-1">
              <p className="font-bold">Audit Diagnostic Notice</p>
              <p>{error}</p>
            </div>
          </div>
        )}

        {/* Audit Results Presentation */}
        {result && (
          <div className="space-y-8 animate-fade-in pt-4 border-t border-slate-200/80">
            {/* Top Score Summary Grid */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              {/* Overall Score Circle */}
              <div className="md:col-span-1 bg-slate-50/90 border border-slate-200/80 rounded-2xl p-6 flex flex-col items-center justify-center text-center space-y-2">
                <span className="text-[11px] font-mono font-bold uppercase text-slate-500 tracking-wider">
                  Overall Health Score
                </span>
                <div className={`w-24 h-24 rounded-full border-4 flex flex-col items-center justify-center font-extrabold ${getScoreColor(result.overallScore)}`}>
                  <span className="text-3xl tracking-tight">{result.overallScore}</span>
                  <span className="text-[10px] uppercase font-mono font-medium -mt-1 text-slate-400">/ 100</span>
                </div>
                <div className="text-xs font-semibold text-slate-700 flex items-center gap-1.5 pt-1">
                  <Clock className="w-3.5 h-3.5 text-slate-400" />
                  <span>{result.responseTimeMs}ms response</span>
                </div>
              </div>

              {/* Sub-scores Metric Pills */}
              <div className="md:col-span-3 grid grid-cols-2 sm:grid-cols-3 gap-3">
                {[
                  { label: "Technical SEO", val: result.scores.technical, icon: ShieldCheck },
                  { label: "On-Page Metadata", val: result.scores.onPage, icon: Layout },
                  { label: "Content Quality", val: result.scores.content, icon: FileCode },
                  { label: "Performance", val: result.scores.performance, icon: Zap },
                  { label: "Social Cards", val: result.scores.social, icon: Share2 },
                  { label: "Structured Data", val: result.scores.structuredData, icon: FileCode }
                ].map((item, idx) => (
                  <div key={idx} className="bg-white border border-slate-200/80 rounded-xl p-3.5 flex flex-col justify-between">
                    <div className="flex items-center justify-between text-slate-500">
                      <span className="text-xs font-medium">{item.label}</span>
                      <item.icon className="w-4 h-4 text-slate-400" />
                    </div>
                    <div className="flex items-baseline justify-between mt-2">
                      <span className="text-xl font-bold text-slate-900">{item.val}</span>
                      <span className={`text-[10px] font-bold font-mono px-1.5 py-0.5 rounded ${
                        item.val >= 80 ? "bg-emerald-50 text-emerald-700" : item.val >= 60 ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700"
                      }`}>
                        {item.val >= 80 ? "Good" : item.val >= 60 ? "Fair" : "Poor"}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Quick Metadata Inspection Strip */}
            <div className="bg-slate-50/60 border border-slate-200/80 rounded-2xl p-5 space-y-4">
              <div className="flex items-center justify-between flex-wrap gap-2">
                <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-700">
                  Inspected Page Signals
                </h3>
                <div className="flex items-center gap-2">
                  <button
                    onClick={copyReport}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 text-xs font-medium cursor-pointer"
                  >
                    {copiedReport ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
                    <span>{copiedReport ? "Report Copied" : "Copy Report"}</span>
                  </button>
                  <button
                    onClick={downloadReport}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 text-xs font-medium cursor-pointer"
                  >
                    <Download className="w-3.5 h-3.5 text-slate-400" />
                    <span>Download JSON</span>
                  </button>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-sans">
                <div className="space-y-1 bg-white p-3.5 rounded-xl border border-slate-200/60">
                  <div className="flex items-center justify-between text-slate-500 text-[11px]">
                    <span className="font-bold">Page Title</span>
                    <span className="font-mono">{result.metadata.titleLength} chars</span>
                  </div>
                  <p className="font-medium text-slate-900 line-clamp-2">
                    {result.metadata.title || <span className="text-rose-500 italic">Missing title tag</span>}
                  </p>
                </div>

                <div className="space-y-1 bg-white p-3.5 rounded-xl border border-slate-200/60">
                  <div className="flex items-center justify-between text-slate-500 text-[11px]">
                    <span className="font-bold">Meta Description</span>
                    <span className="font-mono">{result.metadata.descriptionLength} chars</span>
                  </div>
                  <p className="font-medium text-slate-900 line-clamp-2">
                    {result.metadata.description || <span className="text-rose-500 italic">Missing meta description</span>}
                  </p>
                </div>

                <div className="space-y-1 bg-white p-3.5 rounded-xl border border-slate-200/60">
                  <span className="text-slate-500 text-[11px] font-bold">Canonical Tag</span>
                  <p className="font-mono text-slate-800 truncate">
                    {result.metadata.canonical || <span className="text-amber-500 italic">No canonical tag declared</span>}
                  </p>
                </div>

                <div className="space-y-1 bg-white p-3.5 rounded-xl border border-slate-200/60">
                  <span className="text-slate-500 text-[11px] font-bold">Headings & Media</span>
                  <p className="text-slate-800">
                    <span className="font-semibold">{result.headings.h1Count}</span> H1,{" "}
                    <span className="font-semibold">{result.headings.h2Count}</span> H2,{" "}
                    <span className="font-semibold">{result.media.totalImages}</span> Images ({result.media.missingAltImages} missing alt)
                  </p>
                </div>
              </div>
            </div>

            {/* Categorized Issues & Actionable Fixes */}
            <div className="space-y-4">
              <div className="flex items-center justify-between flex-wrap gap-3">
                <div className="space-y-0.5">
                  <h3 className="text-base font-bold text-slate-900">
                    Audit Findings & Actionable Fixes
                  </h3>
                  <p className="text-xs text-slate-500">
                    Detailed breakdown with severity, rationale, and exact implementation steps.
                  </p>
                </div>

                {/* Filter Tabs */}
                <div className="inline-flex p-1 bg-slate-100 rounded-xl text-xs font-semibold text-slate-600">
                  {[
                    { id: "all", label: `All (${result.issues.length})` },
                    { id: "critical", label: `Critical (${result.issues.filter(i => i.severity === 'critical').length})` },
                    { id: "warning", label: `Warnings (${result.issues.filter(i => i.severity === 'warning').length})` },
                    { id: "good", label: `Passed (${result.issues.filter(i => i.severity === 'good').length})` }
                  ].map((tab) => (
                    <button
                      key={tab.id}
                      onClick={() => setActiveTab(tab.id as any)}
                      className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                        activeTab === tab.id ? "bg-white text-slate-900 shadow-xs font-bold" : "hover:text-slate-900"
                      }`}
                    >
                      {tab.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Issues List */}
              <div className="space-y-3">
                {filteredIssues.map((issue) => (
                  <div
                    key={issue.id}
                    className={`p-4 rounded-2xl border transition-all text-xs font-sans ${
                      issue.severity === "critical"
                        ? "bg-rose-50/40 border-rose-200/80"
                        : issue.severity === "warning"
                        ? "bg-amber-50/40 border-amber-200/80"
                        : "bg-emerald-50/40 border-emerald-200/80"
                    }`}
                  >
                    <div className="flex items-start gap-3">
                      <div className="mt-0.5 shrink-0">
                        {issue.severity === "critical" && <XCircle className="w-4 h-4 text-rose-600" />}
                        {issue.severity === "warning" && <AlertTriangle className="w-4 h-4 text-amber-600" />}
                        {issue.severity === "good" && <CheckCircle2 className="w-4 h-4 text-emerald-600" />}
                      </div>

                      <div className="space-y-2 flex-1">
                        <div className="flex items-center justify-between gap-2 flex-wrap">
                          <h4 className="font-bold text-slate-900 text-sm">{issue.title}</h4>
                          <span className="text-[10px] font-mono uppercase font-bold tracking-wider px-2 py-0.5 rounded-md bg-white border border-slate-200 text-slate-600">
                            {issue.category}
                          </span>
                        </div>

                        <p className="text-slate-600 leading-relaxed">
                          <strong className="text-slate-800">Why it matters:</strong> {issue.whyItMatters}
                        </p>

                        <div className="p-2.5 rounded-xl bg-white/90 border border-slate-200/70 text-slate-800">
                          <strong className="text-[#FF5722] font-mono text-[11px] uppercase block mb-1">
                            Actionable Fix:
                          </strong>
                          <span>{issue.howToFix}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}

                {filteredIssues.length === 0 && (
                  <div className="p-8 text-center bg-slate-50 rounded-2xl border border-slate-200/80 text-slate-500 text-xs">
                    No issues found in this category.
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </ToolShell>
  );
}
